name: CI DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker image
        run: docker build -t node-api:latest .

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .

  scan-trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t node-api:latest .

      - name: Trivy - Scan dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH

      - name: Trivy - Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: node-api:latest
          severity: CRITICAL,HIGH

  conftest:
    runs-on: ubuntu-latest

    - name: Install Conftest
      run: |
        wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_0.52.0_Linux_x86_64.tar.gz
        tar xzf conftest_0.52.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin

    - name: Run Conftest (Kubernetes security policy)
      run: |
        conftest test *.yaml -p policy/
